### ISSUE TITLE
Support for Qwant

### ISSUE THREAD

**Issue by gammore** [Fivefold/linkding-injector#17]
Hi!

First of all, excellent extension! It adds so much functionality to linkding.

Nowadays i'm using more and more Qwant (https://www.qwant.com/) would you be willing to add it to the extension?

Thanks!

**Comment by Fivefold** [comment]
Thank you @gammore, glad you like it!

I took a quick look and Qwant support should be possible without too much trouble. I will earmark it for the next feature update.

**Comment by Fivefold** [comment]
Sorry, @gammore, the earmark got kinda lost for a while. I just added Qwant support in v1.3.4. It's already available on firefox, the chrome web store will receive it probably within the next 24 hours.
